config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :games do
    resources :trackers
  end
  root to: 'static_pages#home'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'trackers', to: 'trackers#index', as: 'trackers'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/update_game', to: 'games#update', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  include SessionsHelper

  belongs_to :metagame
  belongs_to :user
  has_one :tracker

  validates :playtime, presence: true

  scope :get_all_for_user, -> (id) { where(user_id: id) }

  # for every user in the system
  # small solution, not scalable
  def self.update_recent_games
    User.all.each do |user|
      @games, @errors = SteamAPI::Game.get_recently_played_games user
      @games.each do |game|
        metagame = Metagame.find_by_appid(game.appid)
        user_game = metagame.games.where(user_id: user.id).first
        unless user_game.playtime == game.playtime_forever
          user_game.playtime = game.playtime_forever
          user_game.save
          if user_game.tracker.present?
            Tracker.update_tracker(user_game)
          end
        end
      end
    end
  end

end

app/models/metagame.rb
class Metagame < ApplicationRecord
  has_many :games, dependent: :destroy
  
  validates :name, presence: true
  validates :appid, presence: true
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  belongs_to :game

  validates :threshold, presence: true
  validates :base_playtime, presence: true
  validate :validate_days_weeks_months

  def validate_days_weeks_months
    errors.add(:days) if days.blank? && weeks.blank? && months.blank?
  end

  def until
    self.created_at = self.created_at + self.days.days if self.days.present?
    self.created_at = self.created_at + self.weeks.weeks if self.weeks.present?
    self.created_at = self.created_at + self.months.months if self.months.present?
    self.created_at.strftime("%Y-%m-%d")
  end

  def self.check_status_trackers
    Tracker.all.each do |tracker|
      if tracker.until < Time.now
        TrackerMailer.expired_mail(tracker).deliver_now
        tracker.destroy
        p "Tracker expired"
      end
    end
  end

  def self.update_tracker game
    tracker = game.tracker
    tracker.playtime = game.playtime - tracker.base_playtime
    tracker.save
    if tracker.playtime > tracker.threshold
      TrackerMailer.alert_email(tracker).deliver_now
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_many :games, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :steamid, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, presence: true

  # validate correct steam id using api

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_token
    self.remember_token = User.digest(User.new_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include GamesHelper
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def update
    @games, @errors = SteamAPI::Game.get_all_owned_games current_user
    filter_games @games
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      flash[:success] = "You have logged in!"
      redirect_to root_url
    else
      flash[:danger] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    sign_out
    flash[:success] = "You have logged out!"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :signed_in_user, only: :home

  def home
    @games = Game.get_all_for_user(current_user.id)
  end

  def about
  end

end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :signed_in_user

  def index
    @trackers = Tracker.all
  end

  def new
    @game = current_game
    @tracker = Tracker.new
  end

  def create
    @game = current_game
    @tracker = Tracker.new(tracker_params)
    if @tracker.save
      flash[:success] = "You have created a new tracker for #{@game.metagame.name}!"
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @game = current_game
    @tracker = Tracker.find_by(id: params[:id])
  end

  def update
    @game = current_game
    @tracker = Tracker.find_by(id: params[:id])
    if @tracker.update_attributes(tracker_params)
      flash[:success] = "#{@game.metagame.name} tracker updated"
      redirect_to trackers_path
    else
      render 'edit'
    end
  end

  def destroy
    @tracker = Tracker.find_by(id: params[:id])
    @tracker.destroy
    flash[:success] = "Tracker deleted."
    redirect_to trackers_path
  end

  def show
  end

  private

  def tracker_params
    params.require(:tracker).permit(:threshold, :days, :weeks, :months,
                                    :game_id, :base_playtime)
  end

  def current_game
    Game.find_by(id: params[:game_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the SteamTracker app!"
      redirect_to login_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :steamid, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper

  def filter_games games
    games.each do |game|
      if Metagame.find_by_appid(game.appid).nil?
        metagame = Metagame.create(name: game.name, appid: game.appid)
        metagame.games.build(playtime: game.playtime_forever, user_id: current_user.id).save
      else
        metagame = Metagame.find_by_appid(game.appid)
        existing_game = metagame.games.where(user_id: current_user.id).first
         unless existing_game
           metagames.games.build(playtime: game.playtime_forever, user_id: current_user.id).save
         else
           existing_game.playtime = game.playtime_forever
           existing_game.save
         end
      end
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    token = User.new_token
    cookies.permanent[:token] = token
    user.update_attribute(:remember_token, User.digest(token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    token = User.digest(cookies[:token])
    @current_user ||= User.find_by(remember_token: token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in_user
    unless signed_in?
      redirect_to login_path, notice: "Please sign in."
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game/update.html.erb
<h1>Game#update</h1>
<p>Find me in app/views/game/update.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">SteamTracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/trackers" tabindex="-1" aria-disabled="true">Trackers</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    <% if !signed_in? %>
      <%= link_to "Log In", login_path, class: "nav-link" %>
      <%= link_to "Sign Up", signup_path, class: "nav-link" %>
    <% else %>
      <%= link_to "Log Out", logout_path, class: "nav-link" %>
      <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home Page') %>

<%= link_to "Update Game List", update_game_path %>

<table>
  <tr>
    <th>Game Name</th>
    <th>Total Playtime</th>
    <th>Tracker Status</th>
  </tr>
  <% @games.each do |game| %>
    <tr>
      <td><%= game.metagame.name %></td>
      <td><%= game.playtime %></td>
      <% if game.tracker.present?%>
        <td><%= link_to "View tracker", trackers_path %></td>
      <% else %>
        <td><%= link_to "Create tracker", new_game_tracker_path(game) %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/trackers/_fields.html.erb
<%= render 'shared/error_messages', object: f.object%>

<%= f.label :threshold, "Time limit (in hours)" %><span class="required">*</span>
<%= f.number_field :threshold %>

<%= f.label :days %><span class="required">*</span>
<%= f.number_field :days %>

<%= f.label :weeks %><span class="required">*</span>
<%= f.number_field :weeks %>

<%= f.label :months %><span class="required">*</span>
<%= f.number_field :months %>

app/views/trackers/edit.html.erb
<% provide(:title, 'Edit a tracker') %>
<h2>Edit a tracker for <%= @game.metagame.name %></h2>

<div class="row">
  <div class="span6">
    <%= form_for [@game, @tracker] do |f| %>
      <%= render 'fields', f: f %>
      <div><%= f.hidden_field :game_id, value: params[:game_id] %></div>
      <%= f.submit "Edit my tracker", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/trackers/index.html.erb
<% provide(:title, 'Lists of trackers') %>

<table>
  <tr>
    <th>Tracker for</th>
    <th>Limit</th>
    <th>From</th>
    <th>Until</th>
    <th>Current Playtime</th>
  </tr>
  <% @trackers.each do |tracker| %>
    <tr>
      <td><%= tracker.game.metagame.name %></td>
      <td><%= tracker.threshold %></td>
      <td><%= tracker.created_at.strftime("%Y-%m-%d") %></td>
      <td><%= tracker.until %></td>
      <td><%= tracker.playtime %></td>
      <td><%= link_to "Delete", game_tracker_path(tracker.game, tracker), method: :delete %></td>
      <td><%= link_to "Edit", edit_game_tracker_path(tracker.game, tracker) %></td>
    </tr>
  <% end %>
</table>

app/views/trackers/new.html.erb
<% provide(:title, 'Create a tracker') %>
<h2>Create a tracker for <%= @game.metagame.name %></h2>

<div class="row">
  <div class="span6">
    <%= form_for [@game, @tracker] do |f| %>
      <%= render 'fields', f: f %>
      <div><%= f.hidden_field :game_id, value: params[:game_id] %></div>
      <div><%= f.hidden_field :base_playtime, value: @game.playtime %></div>
      <%= f.submit "Create my tracker", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/trackers/show.html.erb
<h1>Trackers#show</h1>
<p>Find me in app/views/trackers/show.html.erb</p>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object%>

<%= f.label :email %><span class="required">*</span>
<%= f.text_field :email %>

<%= f.label :steamid, "Steam ID" %><span class="required">*</span>
<%= f.text_field :steamid %>

<%= f.label :password %><span class="required">*</span>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %><span class="required">*</span>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, 'Update Profile') %>
<h1>Update Profile</h1>

<div class="row">
  <div class="span6">
    <%= form_for @user, controller: 'users', action: 'update' do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save profile", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="span6">
    <%= form_for @user, controller: 'users', action: 'create' do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
    <p>If you already have an account, <%= link_to "Log In", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<h1>Profile page</h1>
<p>User <%= @user.steamid %></p>
<%= link_to "Update Profile", edit_user_path(current_user.id) %>